# docker-compose.yml
version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eth_transactions
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eth_transactions
    volumes:
      - ./data:/var/lib/postgresql/data